[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Enable Next.js runtime for API routes
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all requests to Next.js for handling
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Function configuration for API routes
[functions]
  directory = ".netlify/functions"
  external_node_modules = ["@octokit/rest", "@octokit/auth-app", "openai"]
